---
- name: Ensure .ssh directory exists
  file:
    path: ~/.ssh
    state: directory
- name: Copy ssh private key
  copy:
    src: ../files/id_rsa
    dest: ~/.ssh/id_rsa
    backup: yes
    mode: 0600
- name: Copy ssh public key
  copy:
    src: ../files/id_rsa.pub
    dest: ~/.ssh/id_rsa.pub
    backup: yes
    mode: 0600
