---
- name: Install apt-get packages
  become: true
  apt: name={{ item }} state=present
  with_items:
    - httpie
    - vim
    - openvpn
    - python-pip
- name: Install pip packages
  become: true
  pip: name={{ item }} state=present
  with_items:
    - youtube-dl
