---
- name: Add mono-xamarin apt key
  become: true
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
    state: present
- name: Add mono-xamarin repository
  apt_repository:
    repo: "deb http://download.mono-project.com/repo/debian wheezy main"
    filename: "mono-xamarin"
    state: present
    update_cache: yes
  become: true
- name: Install mono-complete
  become: true
  apt:
    name: mono-complete
    state: present
- name: Add dotnet core key
  become: true
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: 417A0893
    state: present
- name: Add dotnet core repository
  apt_repository:
    repo: "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main"
    filename: "dotnetdev"
    state: present
    update_cache: yes
  become: true
- name: Install dotnet core
  become: true
  apt:
    name: dotnet-dev-1.0.0-preview2.1-003177
    state: present
