---
- name: Install ember cli
  become: true
  npm:
    name: ember-cli
    global: yes
    state: latest
- name: Install bower
  become: true
  npm:
    name: bower
    global: yes
    state: latest
- name: Install phantomjs
  become: true
  npm:
    name: phantomjs-prebuilt
    global: yes
    state: latest
- name: Find out if watchman is installed
  command: "which watchman"
  register: watchman_installed
- name: Clone watchman repository
  git:
    repo: https://github.com/facebook/watchman.git
    clone: yes
    dest: /src/watchman
  when: "{{ watchman_installed.result[0].stdout == 'watchman not found' }}"
- name: Pre-compilation watchman steps
  command: '"{{ item }}" chdir=/src/watchman'
  register: watchman_results
  with_items:
    - ./autogen.sh
    - ./configure
  when: "{{ watchman_installed.result[0].stdout == 'watchman not found' }}"
- name: Compile watchman
  make:
    chdir: /src/watchman
- name: Install watchman
  make:
    chdir: /src/watchman
    target: install
  become: true
  when: "{{ watchman_installed.result[0].stdout == 'watchman not found' }}"
