---
- name: Install build packages and tools
  apt:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - build-essential
    - autotools-dev
    - automake
    - cmake
    - libfreetype6-dev
    - libfontconfig1-dev
    - xclip
    - libtool
    - libssl-dev
    - libxml2-utils
    - tidy
- include: virtualization.yml
- include: python.yml
- include: dotnet.yml
- include: nodejs.yml
- include: tex.yml
- include: crystal.yml
- include: databases.yml
- include: elixir.yml
- include: mancy.yml
- include: pencil.yml
- include: docker.yml
- include: go.yml
