---
- name: Install build packages and tools
  apt:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - build-essential
    - autotools-dev
    - automake
    - cmake
    - libfreetype6-dev
    - libfontconfig1-dev
    - xclip

- include: virtualization.yml
- include: python.yml
- include: dotnet.yml
- include: nodejs.yml
- include: tex.yml
- include: crystal.yml
- include: ember.yml
