---
- include: virtualization.yml
- include: python.yml
- include: dotnet.yml
- include: nodejs.yml
- include: tex.yml
- include: crystal.yml
- include: databases.yml
- include: elixir.yml
- include: mancy.yml
- include: pencil.yml
- include: docker.yml
- include: go.yml
