---
- name: Install Virtualbox
  apt:
    name: virtualbox
    state: present
  become: true
- name: Install Virtualbox extension pack
  apt:
    name: virtualbox-ext-pack
    state: present
  become: true
- name: Install Vagrant
  apt:
    name: vagrant
    state: present
  become: true
