---
- name: Install zsh
  apt:
    name: zsh
    state: present
  become: yes
- name: Change shell to zsh
  user: name=josh shell=/usr/bin/zsh
  become: yes
- name: Ensure directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - ~/bin
- name: Setup oh-my-zsh
  import_tasks: oh_my_zsh.yml
- name: Setup warp directory
  import_tasks: warp_directory.yml
- name: Install Powerline fonts
  import_tasks: powerline_fonts.yml
