---
- name: See if oh-my-zsh is installed
  stat: path=~/.oh-my-zsh
  register: oh_my_zsh_installed
- name: Install Oh-my-zsh
  shell: wget https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | zsh
  ignore_errors: yes
  when: not oh_my_zsh_installed.stat.exists
- name: Set terminal for 256 color
  lineinfile:
    dest: ~/.zshrc
    line: export TERM=xterm-256color
    insertbefore: BOF
    state: present
- name: Clone syntax highlighter plugin
  git:
    repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    clone: yes
    dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
- name: Clone powerlevel9k theme
  git:
    repo: https://github.com/bhilburn/powerlevel9k.git
    clone: yes
    dest: ~/.oh-my-zsh/custom/themes/powerlevel9k
- name: Setup oh-my-zsh theme
  lineinfile:
    dest: ~/.zshrc
    regexp: ^ZSH_THEME=
    line: ZSH_THEME="powerlevel9k/powerlevel9k"
- name: Set powerlevel9k options
  lineinfile:
    dest: ~/.zshrc
    regexp: "{{ item.match }}"
    line:  "{{ item.line }}"
    insertafter: ^ZSH_THEME=
  with_items:
    - match: ^POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=
      line: POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(virtualenv dir vcs status)
    - match: ^POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=
      line: POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()
    - match: ^POWERLEVEL9K_STATUS_VERBOSE=
      line: POWERLEVEL9K_STATUS_VERBOSE=false
    - match: ^POWERLEVEL9K_SHORTEN_DIR_LENGTH=
      line: POWERLEVEL9K_SHORTEN_DIR_LENGTH=3
- name: Set oh-my-zsh plugins
  lineinfile:
    dest: ~/.zshrc
    regexp: ^plugins=
    line: plugins=(git docker wd command-not-found zsh-syntax-highlighting httpie sudo)
- name: Make sure path is setup with ~/bin
  lineinfile:
    dest: ~/.zshrc
    line: export PATH=~/bin:$PATH
- name: alias gpg to gpg2
  lineinefile:
    dest: ~/.zshrc
    line: alias gpg=gpg2
