#!/bin/sh
set -e

if which ansible >/dev/null; then
    echo skipping ansible installation
else
    sudo apt-get install -y software-properties-common
    sudo apt-add-repository ppa:ansible/ansible -y
    sudo apt-get update
    sudo apt-get install -y ansible
fi
