  - name: See if oh-my-zsh is installed
    stat: path=~/.oh-my-zsh
    register: oh_my_zsh_installed

  - name: Install Oh-my-zsh
    shell: wget https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | zsh
    ignore_errors: yes
    when: not oh_my_zsh_installed.stat.exists

  - name: Change shell to zsh
    user: name=josh shell=/usr/bin/zsh
    become: true

  - name: Install Powerline fonts
    include: powerline_fonts.yml

  - name: Clone syntax highlighter plugin
    git:
      repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
      clone: yes
      dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting

  - name: Clone powerlevel9k theme
    git:
      repo: https://github.com/bhilburn/powerlevel9k.git
      clone: yes
      dest: ~/.oh-my-zsh/custom/themes/powerlevel9k

  - name: Ensure Terminator setup for 256 color
    lineinfile:
      dest: ~/.zshrc
      line: "{{ item }}"
      insertbefore: BOF
      state: present
    with_items:
      - export TERM=xterm-256color
      - alias tmux='tmux -2'

  - name: Set oh-my-zsh theme
    lineinfile:
      dest: ~/.zshrc
      regexp: ^ZSH_THEME=
      line: ZSH_THEME="powerlevel9k/powerlevel9k"

  - name: Set powerlevel9k option for left prompt
    lineinfile:
      dest: ~/.zshrc
      regexp: ^POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=
      line: POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(virtualenv dir vcs status)
      insertafter: ^ZSH_THEME=

  - name: Set powerlevel9k option for right prompt
    lineinfile:
      dest: ~/.zshrc
      regexp: ^POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=
      line: POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()
      insertafter: ^ZSH_THEME=

  - name: Set powerlevel9k status option
    lineinfile:
      dest: ~/.zshrc
      regexp: ^POWERLEVEL9K_STATUS_VERBOSE=
      line: POWERLEVEL9K_STATUS_VERBOSE=false
      insertafter: ^ZSH_THEME=

  - name: Set powerlevel9k dir length
    lineinfile:
      dest: ~/.zshrc
      regexp: ^POWERLEVEL9K_SHORTEN_DIR_LENGTH=
      line: POWERLEVEL9K_SHORTEN_DIR_LENGTH=3
      insertafter: ^ZSH_THEME=

  - name: Set oh-my-zsh plugins
    lineinfile:
      dest: ~/.zshrc
      regexp: ^plugins=
      line: plugins=(git docker wd command-not-found zsh-syntax-highlighting httpie sudo)

  - name: Look for warp config file, because ansible sucks in this regard
    stat: path=~/.warprc
    register: warp_config_file

  - name: Ensure Warp Directory config is present
    file: path=~/.warprc state=touch
    when: warp_config_file.stat.exists == false

  - name: Add wd endpoints
    lineinfile:
      dest: ~/.warprc
      line: "{{ item }}"
      insertbefore: EOF
      state: present
    with_items:
      - w:~/workspace
