---
- name: Install pre-requisites
  apt:
    name: ffmpeg
    state: present
  become: yes
- name: Add OBS repository
  apt_repository:
    repo: ppa:obsproject/obs-studio
    filename: obs
    state: present
    update_cache: yes
  become: true
- name: Install obs
  become: true
  apt:
    name: obs-studio
    state: present
