---
- name: Ensure Rider Directory exists
  become: true
  file:
    path: /opt/rider
    state: directory
- name: See if Rider is installed
  stat: path="/opt/rider/Rider-{{ rider_version }}"
  register: rider_present
- name: Download Jetbrains Rider
  become: true
  get_url:
    url: "https://download.jetbrains.com/resharper/JetBrains.Rider-{{ rider_version }}.tar.gz"
    dest: "/opt/rider/rider-{{ rider_version }}.tar.gz"
  when: not rider_present.stat.exists
- name: Decompress Rider
  become: true
  unarchive:
    src: /opt/rider/rider.tar.gz
    dest: /opt/rider
    remote_src: True
  when: not rider_present.stat.exists
- name: Setup rider shortcut
  template:
    src: ../templates/rider.j2
    dest: ~/bin/rider
    mode: 0700
