---
- import_tasks: pencil.yml
- name: Install mancy
  become: yes
  npm:
    name: mancy
    state: present
    global: yes
- name: Install pgadmin
  apt:
    name: pgadmin3
    state: present
  become: yes
- name: Install gitk
  apt:
    name: gitk
    state: present
  become: yes
