---
- name: Add paper themes ppa
  apt_repository:
    repo: "ppa:snwh/pulp"
    state: present
    update_cache: yes
  become: true
- name: Install paper themes
  become: true
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - paper-icon-theme
    - paper-gtk-theme
    - paper-cursor-theme
