# reminder to setup lxd manually: https://bayton.org/2016/05/lxd-zfs-and-bridged-networking-on-ubuntu-16-04-lts/
---
- name: Install Packages
  become: true
  apt:
    name: "{{ item }}"
    state: present
  with_items:
   - lxd
   - zfsutils-linux
   - bridge-utils
