---
- name: Install apt-get packages
  become: true
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - terminator
    - handbrake
    - arandr
    - bleachbit
    - calibre
    - pavucontrol
    - thunar
    - scrot
    - lxappearance
