---
- name: Check if Atom is installed
  stat: path=/usr/bin/atom
  register: atom_present

- name: Download Atom
  get_url:
    url: https://atom.io/download/deb
    dest: /tmp/atom.deb
  when: not atom_present.stat.exists

- name: Install Atom
  command: dpkg -i /tmp/atom.deb
  become: true
  when: not atom_present.stat.exists

- name: Clean up downloaded atom installer
  file: path=/tmp/atom.deb state=absent

- name: Install atom packages
  apm:
    name: "{{ item }}"
  with_items:
    - activate-power-mode
    - advanced-open-file
    - autoclose-html
    - autocomplete-paths
    - chester-atom-syntax
    - editor-stats
    - file-icons
    - git-diff
    - git-log
    - goto-definition
    - highlight-selected
    - language-ansible
    - language-babel
    - language-docker
    - language-gitignore
    - last-cursor-position
    - lines
    - markdown-writer
    - merge-conflicts
    - minimap
    - minimap-cursorline
    - monokai-seti
    - pigments
    - pretty-json
    - seti-icons
    - seti-syntax
    - seti-ui
    - todo-show
    - trailing-spaces
    - wakatime
    - wordcount
    - zentabs

- name: Copy Atom Config
  template:
    src: ../templates/my.atom.config
    dest: ~/.atom/config.cson
