---
- name: Is gitkraken Installed
  stat: path=/usr/bin/gitkraken
  register: gitkraken_present
- name: Download deb installation package
  get_url:
    url: https://release.gitkraken.com/linux/gitkraken-amd64.deb
    dest: /tmp/gitkraken.deb
  when: not gitkraken_present.stat.exists
- name: Install gitkraken
  command: dpkg -i /tmp/gitkraken.deb
  become: true
  when: not gitkraken_present.stat.exists
- name: Clean up
  file: path=/tmp/gitkraken.deb state=absent
- name: Ensure configuration directory exists
  file:
    path: ~/.gitkraken/
    state: directory
- name: Copy configuration file
  copy:
    src: ../files/my.gitkraken.config
    dest: ~/.gitkraken/config
    backup: yes
