---
- name: Install Chrome Dependencies
  apt: pkg={{ item }} state=present
  become: true
  with_items:
    - libxss1
    - libappindicator1
    - libindicator7
- name: Is Chrome Installed
  stat: path=/usr/bin/google-chrome
  register: chrome_present
- name: download chrome
  get_url:
    url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    dest: /tmp/chrome.deb
  when: not chrome_present.stat.exists
- name: install chrome
  command: dpkg -i /tmp/chrome.deb
  become: true
  when: not chrome_present.stat.exists
- name: clean up
  file: path=/tmp/chrome.deb state=absent
