---
- name: Install i3wm and associated tools
  apt:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - i3
    - i3blocks
- name: Ensure i3 config directory exists
  file:
    path: ~/.config/i3
    state: directory
- name: Copy i3 Config
  copy:
    src: ../files/my.i3.config
    dest: ~/.config/i3/config
- name: Copy i3blocks Config
  copy:
    src: ../files/my.i3blocks.config
    dest: ~/.config/i3/i3blocks.conf
- name: Copy lock image
  copy:
    src: ../files/lock.png
    dest: ~/lock.png
- name: Copy lockscreen generator script
  copy:
    src: ../files/generate_lockimg.sh
    dest: ~/bin/generate_lockimg.sh
    mode: 0700
