---
- name: Install NPM
  become: true
  apt: name=npm state=present
- name: Ensure I'm the owner
  become: true
  file: path=~/.npm owner=josh
- name: Create sym-link with node for backward compatibility
  file:
    src: /usr/bin/nodejs
    dest: /usr/bin/node
    state: link
