---
- name: Install gpg and associated tools
  apt:
    name: "{{ item }}"
    state: present
  become: yes
  with_items:
    - gnupg
    - rng-tools
- name: Ensure gpg conf directory exists
  file:
    path: ~/.gnupg
    state: directory
    mode: 0700
- name: setup gnupg conf
  copy:
    src: ../files/gpg.conf
    dest: ~/.gnupg/gpg.conf
    mode: 0600
- name: See if keys are present
  shell: gpg --fast-list-mode --list-keys 2C84D450
  failed_when: false
  changed_when: false
  register: gpg_keys_present
- name: Copy keys over
  copy:
    src: "../files/{{ item }}"
    dest: "~/{{ item }}"
  when: gpg_keys_present.rc != 0
  with_items:
    - pub.key
    - priv.key
- name: Import Keys
  shell: "gpg --import ~/{{ item }}"
  with_items:
    - pub.key
    - priv.key
  when: gpg_keys_present.rc != 0
- name: Clean tmp keys
  file:
    path: "~/{{ item }}"
    state: absent
  with_items:
    - pub.key
    - priv.key
  when: gpg_keys_present.rc != 0
