---
- name: Install slack dependencies
  apt:
    name: gvfs-bin
    state: present
  become: yes
- name: Is slack Installed
  stat: path=/usr/bin/slack
  register: slack_present
- name: Download slack installation package
  get_url:
    url: https://downloads.slack-edge.com/linux_releases/slack-desktop-2.5.2-amd64.deb
    dest: /tmp/slack.deb
  when: not slack_present.stat.exists
- name: Install slack
  command: dpkg -i /tmp/slack.deb
  become: yes
  when: not slack_present.stat.exists
- name: Clean up
  file: path=/tmp/slack.deb state=absent
