---
- name: Add yubikey ppa
  apt_repository:
    repo: "ppa:yubico/stable"
    state: present
    update_cache: yes
  become: true
- name: Install yubikey neo mamanger
  become: true
  apt:
    name: yubikey-neo-manager
    state: present
