---
- name: Install tmux
  become: true
  apt:
    name: tmux
    state: present
- name: Copy tmux config file
  copy:
    src: ../files/my.tmux.config
    dest: ~/.tmux.conf
    backup: no
- name: Setup tmux to assume colors
  lineinfile:
    dest: ~/.zshrc
    line: alias tmux='tmux -2'
