---
- name: Add nodesource apt key
  become: true
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 68576280
    state: present
- name: Add nodesource repository
  become: true
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_6.x xenial main"
    state: present
    update_cache: yes
- name: Install nodejs
  become: true
  apt:
    name: nodejs
    state: present
- name: Add yarn apt key
  become: true
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg
    state: present
- name: Add yarn repository
  become: true
  apt_repository:
    repo: "deb https://dl.yarnpkg.com/debian/ stable main"
    state: present
    update_cache: yes
- name: Install yarn
  become: true
  apt:
    name: yarn
    state: present
- name: Install npm packages
  become: true
  npm:
    name: "{{ item }}"
    global: yes
    state: present
  with_items:
    - bower
    - create-react-app
- name: Find out if watchman is installed
  stat:
    path: /usr/local/bin/watchman
  register: watchman_installed
- name: Clone watchman repository
  git:
    repo: https://github.com/facebook/watchman.git
    clone: yes
    dest: /src/watchman
  when: watchman_installed.stat.exists == False
  become: true
- name: Pre-compilation watchman steps
  command: '"{{ item }}" chdir=/src/watchman'
  register: watchman_results
  with_items:
    - ./autogen.sh
    - ./configure
  become: true
  when: watchman_installed.stat.exists == False
- name: Compile watchman
  make:
    chdir: /src/watchman
  become: true
  when: watchman_installed.stat.exists == False
- name: Install watchman
  make:
    chdir: /src/watchman
    target: install
  become: true
  when: watchman_installed.stat.exists == False
