---
- name: Ensure apt-cache is up to date
  become: true
  apt:
    update_cache: true
    cache_valid_time: 14400 # four hours seems appropriate for a baseline
- name: Install Packages
  become: true
  apt:
    name: "{{ item }}"
    state: present
  with_items:
   - vim
   - httpie
