---
- name: Install Common tools
  apt:
    name: "{{ item }}"
    state: present
  become: yes
  with_items:
    - httpie
    - openvpn
    #- python-pip
    - ntp
    - curl
    - mpv
    - jq
    - cloc
    - w3m
    - lynx
    - htop
    - iftop
    - iotop
    - cmus
    - ranger
    - highlight
    - atool
    - mediainfo
    - mc
    - cowsay
    - cmatrix
    - gconf2
# - name: Install pip packages
#   become: true
#   pip: name={{ item }} state=present
#   with_items:
#     - cryptography
- name: Setup mp3 shortcut
  copy:
    src: ../files/mp3
    dest: ~/bin/mp3
    mode: 0700
- name: Install build packages and tools
  apt:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - build-essential
    - autotools-dev
    - automake
    - cmake
    - libfreetype6-dev
    - libfontconfig1-dev
    - xclip
    - libtool
    - libssl-dev
    - libxml2-utils
    - tidy
