- name: Install Cowsay
  become: true
  apt: name=cowsay state=present

- name: Activate Random Cowsay
  lineinfile:
    dest: ~/.profile
    line: export ANSIBLE_COW_SELECTION=random

- name: Install Parrotsay
  become: true
  npm:
    name: parrotsay
    global: yes
    state: present
