---
- name: Add atom ppa
  apt_repository:
    repo: "ppa:webupd8team/atom"
    state: present
    update_cache: yes
  become: true
- name: Install or Update Atom to latest
  become: true
  apt:
    name: atom
    state: latest
- name: Install atom packages
  apm:
    name: "{{ item }}"
  with_items:
    - activate-power-mode
    - advanced-open-file
    - autoclose-html
    - autocomplete-paths
    - autocomplete-python
    - chester-atom-syntax
    - editor-stats
    - file-icons
    - git-diff
    - git-log
    - goto-definition
    - highlight-selected
    - language-ansible
    - language-babel
    - language-docker
    - language-gitignore
    - language-javascript
    - language-sass
    - last-cursor-position
    - lines
    - linter
    - linter-eslint
    - linter-ui-default
    - markdown-writer
    - merge-conflicts
    - minimap
    - minimap-cursorline
    - monokai-seti
    - pigments
    - pretty-json
    - seti-icons
    - seti-syntax
    - seti-ui
    - todo-show
    - trailing-spaces
    - wordcount
- name: Copy Atom Config
  copy:
    src: ../files/my.atom.config
    dest: ~/.atom/config.cson
