#!/usr/bin/env python
import argparse
import subprocess
import socket

hostname = socket.gethostname()

parser = argparse.ArgumentParser(description='My Ansible Provisioner')

playbook_file = 'workstation.yml'
command = 'ansible-playbook -l ' + hostname + ' ' + playbook_file
retcode = subprocess.call(command, shell = True)
exit(retcode)
