#!/usr/bin/env bash

TEMPLATE_DIRECTORY=roles/packages/files

# ATOM
ATOM_TARGET=my.atom.config
ATOM_PATH="$TEMPLATE_DIRECTORY/$ATOM_TARGET"
if [ -f "$ATOM_PATH" ]; then
    rm "$ATOM_PATH"
fi
cp ~/.atom/config.cson $ATOM_PATH


# GIT
GIT_TARGET=my.gitconfig
GIT_PATH="$TEMPLATE_DIRECTORY/$GIT_TARGET"
if [ -f "$GIT_PATH" ]; then
    rm "$GIT_PATH"
fi
cp ~/.gitconfig $GIT_PATH


# TERMINATOR
TERMINATOR_TARGET=my.terminator.config
TERMINATOR_PATH="$TEMPLATE_DIRECTORY/$TERMINATOR_TARGET"
if [ -f "$TERMINATOR_PATH" ]; then
    rm "$TERMINATOR_PATH"
fi
cp ~/.config/terminator/config $TERMINATOR_PATH


# VIM
VIM_TARGET=my.vimrc
VIM_PATH="$TEMPLATE_DIRECTORY/$VIM_TARGET"
if [ -f "$VIM_PATH" ]; then
    rm "$VIM_PATH"
fi
cp ~/.vimrc $VIM_PATH

# tmux
TMUX_TARGET=my.tmux.config
TMUX_PATH="$TEMPLATE_DIRECTORY/$TMUX_TARGET"
if [ -f "$TMUX_PATH" ]; then
    rm "$TMUX_PATH"
fi
cp ~/.tmux.conf $TMUX_PATH

# i3
I3_TARGET=my.i3.config
I3_PATH="$TEMPLATE_DIRECTORY/$I3_TARGET"
if [ -f "$I3_PATH" ]; then
    rm "$I3_PATH"
fi
cp ~/.config/i3/config $I3_PATH

# i3
I3BLOCKS_TARGET=my.i3blocks.config
I3BLOCKS_PATH="$TEMPLATE_DIRECTORY/$I3BLOCKS_TARGET"
if [ -f "$I3BLOCKS_PATH" ]; then
    rm "$I3BLOCKS_PATH"
fi
cp ~/.config/i3/i3blocks.conf $I3BLOCKS_PATH
