---
- hosts: all
  roles:
    - apt_setup
    - sshkeys
    - demonreach_ca
    - gpg
    - diskutils
    - zsh
    - tmux
    - vim
    - commandline
    - docker
    - dotnet
    - golang
    - python
    - elixir
    - nodejs
    - crystal
    - xorg
    - i3wm
    - tex
    - zork
    - xkcd
    - jetbrains_rider
    - visualdevtools
    - virtualbox
    - vagrant
