---
- hosts: all
  roles:
    - apt_setup
    - sshkeys
    - demonreach_ca
    - gpg
    - diskutils
    - zsh
    - tmux
    - vim
    - commandline
    - git
    - docker
    - dotnet
    - golang
    - python
    - elixir
    - nodejs
    - parrotsay
    - crystal
    - gnome_keyring
    - xorg
    - firacode
    - i3wm
    - infinality
    - terminator
    - google_chrome
    - atom
    - role: tex
      when: install_tex
    - zork
    - xkcd
    - graphical_utilities
    - jetbrains_rider
    - robo3t
    - insomnia
    - remmina
    - visualdevtools
    - disk_encryption
    - network_ui
    - keybase.io
    - enpass
    - yubikey
    - virtualbox
    - vagrant
    - graphics_apps
    - bibisco
    - software_defined_radio
    - slack
    - OpenBroadcasterSystem
    - role: makemkv
      when: install_makemkv
    - role: private_internet_access
      when: install_pia
