---
- hosts: all
  roles:
    - apt_setup
    - sshkeys
    - demonreach_ca
    - gpg
    - diskutils
    - zsh
    - tmux
    - vim
    - commandline
    - docker
    - python
    - xorg
    - i3wm
    - zork
    - xkcd
