---
- hosts: all
  roles:
    - apt_setup
    - sshkeys
    - demonreach_ca
    - gpg
    - diskutils
    - zsh
    - tmux
    - vim
    - commandline
    - git
    - docker
    - dotnet
    - golang
    - python
    - elixir
    - nodejs
    - parrotsay
    - crystal
    - gnome_keyring
    - xorg
    - i3wm
    - infinality
    - terminator
    - google_chrome
    - atom
    - tex
    - zork
    - xkcd
    - graphical_utilities
    - jetbrains_rider
    - remmina
    - visualdevtools
    - disk_encryption
    - keybase.io
    - enpass
    - yubikey
    - virtualbox
    - vagrant
    - graphics_apps
    - bibisco
    - software_defined_radio
    - slack
    - makemkv
    - private_internet_access
