---
- name: See if keys exist to prevent accidental overwrite of other keys
  stat:
    path: ~/.ssh/id_rsa
  register: ssh_key_exist
- name: Ensure .ssh directory exists
  file:
    path: ~/.ssh
    state: directory
- name: Copy ssh private key
  copy:
    src: ../files/id_rsa
    dest: ~/.ssh/id_rsa
    backup: yes
  when: not ssh_key_exist.stat.exists
- name: Copy ssh public key
  copy:
    src: ../files/id_rsa.pub
    dest: ~/.ssh/id_rsa.pub
    backup: yes
  when: not ssh_key_exist.stat.exists
- name: Add key to ssh agent
  lineinfile:
    dest: /home/josh/.zshrc
    line: "{{ item }}"
  with_items:
    - eval "$(ssh-agent)"
    - ssh-add ~/.ssh/id_rsa
