---
- name: Add ppa
  apt_repository:
    repo: ppa:heyarje/makemkv-beta
    filename: "makemkv"
    state: present
    update_cache: yes
  become: yes
- name: Install Packages
  apt:
    name: "{{ item }}"
    state: present
  become: yes
  with_items:
    - makemkv-oss
    - makemkv-bin
